### ISSUE TITLE
"sqlite3.DatabaseError: " sporadic issues

### ISSUE THREAD

**Issue by Krisscut** [deckar01/ratelimit#8]
Hi !

Thanks for your work !

I'm using it in a multithreaded environment, and i sometimes have those weird errors:

`17:20:38 ERR [MainThread][script.py:445][main] .... Catched unsupported exception: <class 'sqlite3.DatabaseError'>.
Traceback (most recent call last):
  File "script/venv/lib/python3.6/site-packages/ratelimit/decorators.py", line 150, in wrapper
    return func(*args, **kargs)
  File "script/venv/lib/python3.6/site-packages/ratelimit/decorators.py", line 109, in wrapper
    self.database.execute("BEGIN TRANSACTION")
sqlite3.DatabaseError: not an error
`

`17:19:09 [1;31mERR[0m [Worker-2][script.py:163][work] .............................. Catched unsupported exception : [1;31m<class 'sqlite3.DatabaseError'>[0m.
Traceback (most recent call last):
  File "script/venv/lib/python3.6/site-packages/ratelimit/decorators.py", line 150, in wrapper
    return func(*args, **kargs)
  File "script/venv/lib/python3.6/site-packages/ratelimit/decorators.py", line 109, in wrapper
    self.database.execute("BEGIN TRANSACTION")
sqlite3.DatabaseError: cannot start a transaction within a transaction`

Do you have any idea what could be the issue ?

**Comment by deckar01** [comment]
The `BEGIN TRANSACTION` does appear to be redundant. The connection's context manager `with self.database` should be all that is needed. I'm surprised it doesn't warn me (or the unit tests) about this, so I wouldn't be too surprised if this was caused by an implementation being strict about it.

What python version / implementation are you using? What module are you using for multithreading?

Could you try commenting out `self.database.execute("BEGIN TRANSACTION")` in your site packages and see if that resolves the issue?

https://github.com/deckar01/ratelimit/blob/15068f4/ratelimit/decorators.py#L109

**Comment by Krisscut** [comment]
Yes indeed it could be dependent on the environment.
I'm on python 3.6.2.

it's a bit late, but i try to comment the line and see how it goes tomorrow.

Thanks for the fast answer !

**Comment by Krisscut** [comment]
Since i made the modification, i never reproduced the issue again (yet) after multiple runs.

**Comment by Krisscut** [comment]
Thanks for the fast support !  😊
I saw the new release, will try it next Monday. Have a nice weekend !
